feat(Timeslot) Timeslot V1 with 2 ranges but no margin option
pluginsGLPI/deploy pull request #22
Opened 2024-02-01 16:03 UTC by Lainow

![image](https://github.com/pluginsGLPI/deploy/assets/107540223/2220d65d-ad1a-47a9-969e-c54747867b97)

2024-02-12 08:39 UTC, stonebuzz commented
@cconard96 

I'd like your review of the JS part (it's not my area of expertise =) )

2024-02-12 10:04 UTC, cconard96 requested changes

2024-02-21 10:41 UTC, stonebuzz commented
@Lainow 

as a final step with a final review 

We need to add ```glpi_plugin_deploy_timeslots_id``` column to table ```glpi_plugin_deploy_package_target.php```

add update this view 

![image](https://github.com/pluginsGLPI/deploy/assets/7335054/cfeda480-9b9b-43cf-8de1-6a35013f766c)

to choose the timeslot when selecting the computer group 

and display it in the table below

2024-02-29 08:34 UTC, stonebuzz commented
@Lainow 

waiting for the CI Continuous integration to be adapted to GLPI 11.0.x

2024-02-29 09:55 UTC, merged